### ISSUE TITLE
Change log level to info at PlayStoreAppUpdateAvailabilityChecker.java:26

### ISSUE THREAD

**Issue by ankitbatra11** [ankitbatra11/wheelie#206]
```
Non-fatal Exception: e.g.a.e.a.d.a: Install Error(-9): The Play Store app is either not installed or not the official version. (https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#ERROR_PLAY_STORE_NOT_FOUND)
       at com.google.android.play.core.appupdate.o.i(o.java:2)
       at com.google.android.play.core.appupdate.o.a(o.java:1)
       at com.google.android.play.core.appupdate.d.getAppUpdateInfo(d.java:1)
       at com.abatra.android.wheelie.appUpdate.playStore.PlayStoreAppUpdateAvailabilityChecker.checkAppUpdateAvailability(PlayStoreAppUpdateAvailabilityChecker.java:26)
       at com.abatra.android.wheelie.appUpdate.playStore.PlayStoreAppUpdateHandler.checkAppUpdateAvailability(PlayStoreAppUpdateHandler.java:48)
```

**Comment by ankitbatra11** [comment]
It's coming from play core library.
