### ISSUE TITLE
Initialize singlePermissionRequestor and multiplePermissionRequestor in observeLifecycle call itself

### ISSUE THREAD

**Issue by ankitbatra11** [ankitbatra11/wheelie#38]

**Comment by ankitbatra11** [comment]
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.launch(java.lang.Object)' on a null object reference
        at com.abatra.android.wheelie.permission.AbstractSinglePermissionRequestor.requestSystemPermission(AbstractSinglePermissionRequestor.java:68)
        at com.abatra.android.wheelie.permission.ManifestSinglePermissionRequestor.requestSystemPermission(ManifestSinglePermissionRequestor.java:8)
        at com.abatra.android.wheelie.permission.ManifestPermissionRequestor.requestSystemPermission(ManifestPermissionRequestor.java:33)
        at a.b.c.service.permission.RequestPermissionsActivity.onCreate(RequestPermissionsActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:7820)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3363)
```
